# Dependencies
gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
#markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Peace CG'
tagline:          'A Jekyll theme'
description:      'A Computer Graphics research for Vegan and Peace.'
url:              https://crystalsu2008.github.io
baseurl:          /

author:
  name:           'Chris Su'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
