# Dependencies
gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Celestial CG'
tagline:          'A Jekyll theme'
description:      'Be Vegan, Make Peace. <br>My personal blog about 3D graphics research.'
url:              https://crystalsu2008.github.io
baseurl:          /

author:
  name:           'Chris Su'
  url:            https://twitter.com/crystalsu2008

paginate:         5

# Custom vars
hyde_version:          2.1.0

github:
  repo:           https://github.com/crystalsu2008/crystalsu2008.github.io

hyde_repo:        https://github.com/poole/hyde
